language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sh -c "if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ;fi"
  - composer self-update
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}

install: composer install
