dist: trusty
sudo: false
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5    
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.1
          env: DEPENDENCIES='dev'
        # Test LTS version
        - php: 5.6
          env: SYMFONY_VERSION='^2'
        - php: 7.1
          env: SYMFONY_VERSION='^3'

before_install:
  - if [ `php-config --vernum` -ge 50500 ] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi;
  - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/lts:${SYMFONY_VERSION} --no-update; fi;

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
